### ISSUE TITLE
Syntax error in line 1

### ISSUE THREAD

**Issue by noodlebreak** [Alexander-0x80/resume-bandit#1]
```
/usr/local/bin/resume-bandit: line 1: syntax error near unexpected token `('
'usr/local/bin/resume-bandit: line 1: `var fs   = require("fs");
```

Note: I'm not very well versed with Node and related things, but a friend told me to try this:
    npm install -g fs
which is supposed to install fs module system wide.
It didn't solve the problem.

**Comment by Alexander-0x80** [comment]
Could you please explain how can i reproduce this ?

**Comment by AdamHess** [comment]
fs is native to nodejs you shouldn't have to install fs 

more likely you decided to edit the code and made a change to the text...your error message is incomplete. Please repast the entire thing.

**Comment by uxtx** [comment]
FWIW, I'm able to duplicate @noodlebreak's error. This was off of a freshly brewed (im on a mac) copy of node and a clean `npm install -g resume-bandit`

```
My-Mac:Work$ npm install -g resume-bandit
/usr/local/bin/resume-bandit -> /usr/local/lib/node_modules/resume-bandit/src/bandit.js
resume-bandit@0.0.2 /usr/local/lib/node_modules/resume-bandit
├── underscore@1.8.3
├── commander@2.8.1 (graceful-readlink@1.0.1)
└── js-yaml@3.3.1 (esprima@2.2.0, argparse@1.0.2)

My-Mac:Work$ resume-bandit
/usr/local/bin/resume-bandit: line 1: syntax error near unexpected token `('
'usr/local/bin/resume-bandit: line 1: `var fs   = require("fs");
My-Mac:Work$ node -v
v0.12.4

```

**Comment by noodlebreak** [comment]
I was just trying to run it, tried running with help option, and I got that error.

@TheSpiderPig, no, the error message isn't incomplete. That's all I got on running the command.

```
(ubuntu)-(jobs:0)-(~)-(19:50:43)
 (1997)-> resume-bandit
/usr/local/bin/resume-bandit: line 1: syntax error near unexpected token `('
'usr/local/bin/resume-bandit: line 1: `var fs   = require("fs");
```

**Comment by abankspdx** [comment]
Seconded.

Output:

```
Alexs-MacBook-Air:resume alex$ resume-bandit -d resume.yaml
/usr/local/bin/resume-bandit: line 1: syntax error near unexpected token `('
'usr/local/bin/resume-bandit: line 1: `var fs   = require("fs");
```

**Comment by remimarenco** [comment]
:+1:

**Comment by Alexander-0x80** [comment]
i'll try to get around a mac to test this issue , could not reproduce it on my win8 and ubuntu boxes.

**Comment by noodlebreak** [comment]
@Alexander-0x80, have you hosted this anyhwere? It would be great to try out for demo.

**Comment by Alexander-0x80** [comment]
i guess it would be nice to have, i will get on it

**Comment by noodlebreak** [comment]
Any updates yet, @Alexander-0x80 ?

**Comment by Alexander-0x80** [comment]
I guess it should work on mac's now ..  can anyone check this out ?
pushing to github from windows added some strange line breaks
