### ISSUE TITLE
executing program opens default js editor

### ISSUE THREAD

**Issue by Kehet** [Alexander-0x80/resume-bandit#2]
I tried to launch resume-bandit from windows commandline, but command just tries to execute bandit.js, which opens PhpStorm (probably just my default js editor) and waits that to close.

It looks like this

``` cmd
M:\My Programs\resumebandit>resume-bandit
M:\My Programs\resumebandit>"C:\Users\kehet\AppData\Roaming\npm\\node_modules\resume-bandit\src\bandit.js"
```

then it opens that js file using my IDE, waits that process to close and then exits with exit code 0. No files are generated to current directory. Any options wont change behavior.

I'm using Windows 7. NPM resolves these versions

```
resume-bandit@0.0.2 C:\Users\kehet\AppData\Roaming\npm\node_modules\resume-bandit
├── underscore@1.8.3
├── commander@2.8.1 (graceful-readlink@1.0.1)
└── js-yaml@3.3.1 (esprima@2.2.0, argparse@1.0.2)
```

**Comment by Alexander-0x80** [comment]
a67cea23e044043abf49133b309cb41c899f89b5 solves this issue
